#!/usr/bin/env python3
"""
Convert an image into a C file that can be compiled into the firmware (LVGL v9).

Static images (PNG, BMP, JPG, ...) are converted to RGB565 pixels.
Animated GIFs are embedded as-is and decoded on the device.

Usage:
    python3 tools/img2c.py imgs/home.bmp
    python3 tools/img2c.py imgs/evileye.gif --name evileye -o core/media/images

The variable name defaults to the file name (without extension). That name is
what you add to core/media/image_list.c.

Needs Pillow:  pip install pillow
"""

import argparse
import os
import re
import sys

from PIL import Image

BYTES_PER_LINE = 16


def c_name(path):
    name = os.path.splitext(os.path.basename(path))[0]
    name = re.sub(r"\W", "_", name)
    if name[0].isdigit():
        name = "_" + name
    return name


def rgb565(img):
    """Pixels as little-endian RGB565, the byte order LVGL uses in memory.
    Each channel is rounded to the nearest value, like LVGL's online converter.
    Transparency is ignored."""
    img = img.convert("RGB")
    out = bytearray()
    for r, g, b in img.getdata():
        v = (min(31, (r + 4) >> 3) << 11) | (min(63, (g + 2) >> 2) << 5) | min(31, (b + 4) >> 3)
        out += bytes((v & 0xFF, v >> 8))
    return out


def hex_lines(data):
    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("image")
    ap.add_argument("--name", help="C variable name (default: file name)")
    ap.add_argument("-o", "--out-dir", default="core/media/images", help="output folder (default: %(default)s)")
    args = ap.parse_args()

    name = args.name or c_name(args.image)
    img = Image.open(args.image)
    w, h = img.size
    is_gif = img.format == "GIF"

    if is_gif:
        with open(args.image, "rb") as f:
            data = f.read()
        cf, stride, kind = "LV_COLOR_FORMAT_RAW", 0, "GIF, decoded on the device"
    else:
        data = rgb565(img)
        cf, stride, kind = "LV_COLOR_FORMAT_RGB565", w * 2, "RGB565"

    src = f"""/* {name}: {w}x{h} {kind}. Generated by tools/img2c.py from {os.path.basename(args.image)} */

#include "lvgl.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{
{hex_lines(data)}
}};

const lv_image_dsc_t {name} = {{
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = {cf},
    .header.flags = 0,
    .header.w = {w},
    .header.h = {h},
    .header.stride = {stride},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};
"""
    os.makedirs(args.out_dir, exist_ok=True)
    out_path = os.path.join(args.out_dir, name + ".c")
    with open(out_path, "w") as f:
        f.write(src)

    print(f"{out_path}: {name}, {w}x{h}, {'animated GIF' if is_gif else 'static image'}, {len(data)} bytes")
    if w > 240 or h > 240:
        print("  note: larger than the 240x240 screen", file=sys.stderr)


if __name__ == "__main__":
    main()
